#!/bin/bash

CHALLENGE=${CHALLENGE:-"http-01"}

[ ! -d $WELLKNOWN ] && mkdir -p $WELLKNOWN
if [ ! -f /etc/letsencrypt/config.sh ]; then
  if [ -n "$CA" ]; then
  echo "CA=$CA" >> /etc/letsencrypt/config.sh
  fi
  echo "WELLKNOWN=$WELLKNOWN" >> /etc/letsencrypt/config.sh
fi
cd /etc/letsencrypt/
echo > domains.txt
for name in $( echo ${COMMON_NAMES} |tr ',' ' '); do
    echo "${name} ${ALTERNATIVE_NAMES}" >> domains.txt 
done
while true; do
    args=" --config /etc/letsencrypt/config.sh --challenge $CHALLENGE -c"
    if [ "$CHALLENGE" == "dns-01" ]; then
        args="$args --hook /usr/local/bin/hook-nsupdate.sh"
    fi
    /usr/local/bin/dehydrated $args
    sleep 10d
done
