#!/bin/bash

if [ ! -f /etc/letsencrypt/config.sh ]; then
  if [ -n "$CA" ]; then
  echo "CA=$CA" >> /etc/letsencrypt/config.sh
  fi
  echo "WELLKNOWN=$WELLKNOWN" >> /etc/letsencrypt/config.sh
fi
cd /etc/letsencrypt/
while [ true ]; do
  for name in ${COMMON_NAMES}; do
    /usr/local/bin/letsencrypt.sh -c -d ${COMMON_NAMES} -t http-01
  done
  sleep 10d
done
