#!/bin/bash

[ ! -d $WELLKNOWN ] && mkdir -p $WELLKNOWN
if [ ! -f /etc/letsencrypt/config.sh ]; then
  if [ -n "$CA" ]; then
  echo "CA=$CA" >> /etc/letsencrypt/config.sh
  fi
  echo "WELLKNOWN=$WELLKNOWN" >> /etc/letsencrypt/config.sh
fi
cd /etc/letsencrypt/
while true; do
  for name in $( echo ${COMMON_NAMES} |tr ',' ' '); do
    /usr/local/bin/dehydrated --config /etc/letsencrypt/config.sh -c -d ${name} -t http-01
  done
  sleep 10d
done
